In [1]:
import pandas as pd
import re
from yahoofinancials import YahooFinancials

In [2]:
ticker = "PETR4.SA"
yf = YahooFinancials(ticker)

In [3]:
income_statment_data_a = yf.get_financial_stmts("annual", "income")
balance_sheet_data_a = yf.get_financial_stmts("annual", "balance")
cash_flow_data_a = yf.get_financial_stmts("annual", "cash")

In [4]:
def yf_to_pd(x):
    x = next(iter(next(iter(x.values())).values()))
    
    df_list = []
    
    for i in x:
        df_list.append(pd.DataFrame.from_dict(i, orient="index"))
    
    return pd.concat(df_list).transpose()

In [5]:
petr_is = yf_to_pd(income_statment_data_a)
petr_is.sort_index(axis=1, inplace=True)

In [6]:
petr_bs = yf_to_pd(balance_sheet_data_a)
petr_bs.sort_index(axis=1, inplace=True)

In [7]:
petr_cf = yf_to_pd(cash_flow_data_a)
petr_cf.sort_index(axis=1, inplace=True)

In [8]:
def change_index(n):
    return " ".join(re.findall("[A-Z][^A-Z]*", (n[0].upper() + n[1:])))

In [9]:
petr_is.index = petr_is.index.map(change_index)
petr_bs.index = petr_bs.index.map(change_index)
petr_cf.index = petr_cf.index.map(change_index)

In [10]:
petr_is

,2017-12-31,2018-12-31,2019-12-31,2020-12-31
Research Development,1831000000,2345000000,2268000000,1819000000
Effect Of Accounting Charges,None,None,None,None
Income Before Tax,6174000000,38967000000,47242000000,37000000
Minority Interest,5624000000,6318000000,3596000000,2740000000
Net Income,-446000000,25779000000,40137000000,7108000000
Selling General Administrative,23824000000,22084000000,26114000000,30545000000
Gross Profit,91595000000,118687000000,122105000000,123962000000
Ebit,48004000000,70668000000,77770000000,80400000000
Operating Income,48004000000,70668000000,77770000000,80400000000
Other Operating Expenses,13411000000,16192000000,13707000000,-7274000000
Interest Expense,-16602000000,-14980000000,-13810000000,-13702000000
Extraordinary Items,None,None,None,None
Non Recurring,None,None,None,None
Other Items,None,None,None,None
Income Tax Expense,5797000000,15462000000,16400000000,-6209000000
Total Revenue,258454000000,310255000000,263827000000,242146000000
Total Operating Expenses,210450000000,239587000000,186057000000,161746000000
Cost Of Revenue,166859000000,191568000000,141722000000,118184000000
Total Other Income Expense Net,-41830000000,-31701000000,-30528000000,-80363000000
Discontinued Operations,3193000000,3193000000,10128000000,None
Net Income From Continuing Ops,377000000,23505000000,30842000000,6246000000
Net Income Applicable To Common Shares,-446000000,25779000000,40137000000,7108000000

In [11]:
petr_bs

,2017-12-31,2018-12-31,2019-12-31,2020-12-31
Intangible Assets,7020000000,10084000000,78237000000,77553000000
Total Liab,561906000000,576930000000,626874000000,676269000000
Total Stockholder Equity,263985000000,277225000000,295541000000,308410000000
Minority Interest,5624000000,6318000000,3596000000,2740000000
Other Current Liab,20804000000,36209000000,29433000000,18000000000
Total Assets,831515000000,860473000000,926011000000,987419000000
Common Stock,205432000000,205432000000,205432000000,205432000000
Other Current Assets,22589000000,20585000000,18584000000,13111000000
Retained Earnings,77364000000,95364000000,124829000000,127512000000
Other Liab,141132000000,167282000000,200705000000,198798000000
Good Will,720000000,786000000,252000000,125000000
Treasury Stock,-18811000000,-23571000000,-34720000000,-24534000000
Other Assets,70744000000,85273000000,71074000000,104747000000
Cash,74494000000,53854000000,29714000000,60856000000
Total Current Liabilities,82535000000,97068000000,116147000000,136287000000
Deferred Long Term Asset Charges,11373000000,10384000000,5593000000,33524000000
Short Long Term Debt,23160000000,14207000000,18013000000,21751000000
Other Stockholder Equity,-18811000000,-23571000000,-34720000000,-24534000000
Property Plant Equipment,584357000000,609829000000,641949000000,645434000000
Total Current Assets,155909000000,143606000000,112101000000,142323000000
Long Term Investments,12765000000,10895000000,22398000000,17237000000
Net Tangible Assets,256245000000,266355000000,217052000000,230732000000
Short Term Investments,2015000000,4198000000,3580000000,3424000000
Net Receivables,24508000000,30147000000,27214000000,35432000000
Long Term Debt,337564000000,311954000000,236969000000,258287000000
Inventory,28081000000,34822000000,33009000000,29500000000
Accounts Payable,19077000000,24516000000,22576000000,35645000000

In [12]:
petr_cf

,2017-12-31,2018-12-31,2019-12-31,2020-12-31
Investments,-2961000000,2119000000,808000000,-4957000000
Change To Liabilities,-160000000,3557000000,-3821000000,2178000000
Total Cashflows From Investing Activities,-35218000000,-17788000000,-7952000000,-23455000000
Net Borrowings,-28624000000,-83296000000,-98594000000,-78831000000
Total Cash From Financing Activities,-46482000000,-107040000000,-126336000000,-101773000000
Change To Operating Activities,-2511000000,-7000000000,-28262000000,9361000000
Net Income,-446000000,25779000000,40137000000,7108000000
Change In Cash,5386000000,-20640000000,-24125000000,31201000000
Effect Of Exchange Rate,619000000,8342000000,8397000000,8323000000
Total Cash From Operating Activities,86467000000,95846000000,101766000000,148106000000
Depreciation,44810000000,49289000000,60677000000,74784000000
Other Cashflows From Investing Activities,1450000000,3438000000,47342000000,1264000000
Dividends Paid,-2368000000,-2368000000,-7488000000,-6209000000
Change To Inventory,-1130000000,-7599000000,-1208000000,4309000000
Change To Account Receivables,-3140000000,-5983000000,8578000000,-913000000
Other Cashflows From Financing Activities,-17858000000,-21376000000,-20254000000,-16733000000
Change To Netincome,51174000000,39161000000,34548000000,52640000000
Capital Expenditures,-43614000000,-43561000000,-34010000000,-29974000000